# Generated by Django 4.2.11 on 2024-05-27 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loyixa', '0004_alter_zapchast_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxsulot',
            name='brand_image',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='maxsulot',
            name='status',
            field=models.TextField(default='False'),
        ),
        migrations.AddField(
            model_name='zapchast',
            name='status',
            field=models.BooleanField(default='False'),
        ),
        migrations.AlterField(
            model_name='zapchast',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=50)),
                ('maxsulot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loyixa.maxsulot')),
            ],
        ),
    ]
