# Generated by Django 4.2.11 on 2024-06-05 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyixa', '0005_maxsulot_brand_image_maxsulot_image_maxsulot_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maxsulot',
            name='brand_image',
            field=models.FileField(null=True, upload_to='brand_images'),
        ),
        migrations.AlterField(
            model_name='maxsulot',
            name='image',
            field=models.FileField(null=True, upload_to='images'),
        ),
    ]
