# Generated by Django 4.2.11 on 2024-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyixa', '0006_alter_maxsulot_brand_image_alter_maxsulot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapchast',
            name='image',
            field=models.FileField(upload_to='zapchast_image'),
        ),
    ]
